"""Constants for the Janitza UMG 604-PRO integration."""

DOMAIN = "janitza_umg604"
PLATFORMS = ["sensor"]

CONF_UNIT_ID = "unit_id"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_ADDRESS_OFFSET = "address_offset"

DEFAULT_PORT = 502
DEFAULT_UNIT_ID = 1
DEFAULT_SCAN_INTERVAL = 10
DEFAULT_ADDRESS_OFFSET = 0

MIN_SCAN_INTERVAL = 2
MAX_SCAN_INTERVAL = 300

